"""empty message

Revision ID: 026bbd098c79
Revises: 2801e7bf2187
Create Date: 2021-01-03 20:02:33.828105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026bbd098c79'
down_revision = '2801e7bf2187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    # ### end Alembic commands ###
